# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import visualize.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fieldname', models.CharField(max_length=200)),
                ('data_filename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_uses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc1', visualize.fields.SeparatedValuesField()),
                ('bc2', visualize.fields.SeparatedValuesField()),
                ('dt', models.TextField()),
                ('dx', visualize.fields.SeparatedValuesField()),
                ('eplasticity', models.TextField()),
                ('faultnormal', models.TextField()),
                ('friction', models.TextField()),
                ('ihypo', visualize.fields.SeparatedValuesField()),
                ('np3', visualize.fields.SeparatedValuesField()),
                ('npml', models.TextField()),
                ('nt', models.TextField()),
                ('vp', models.TextField()),
                ('vs', models.TextField()),
                ('rho', models.TextField()),
                ('x1', models.TextField(blank=True, null=True)),
                ('x2', models.TextField(blank=True, null=True)),
                ('x3', models.TextField(blank=True, null=True)),
                ('tn', models.TextField(blank=True, null=True)),
                ('ts', models.TextField(blank=True, null=True)),
                ('pcdep', models.TextField(blank=True, null=True)),
                ('rcrit', models.TextField(blank=True, null=True)),
                ('delts', models.TextField(blank=True, null=True)),
                ('tm0', models.TextField(blank=True, null=True)),
                ('tmnucl', models.TextField(blank=True, null=True)),
                ('trelax', models.TextField(blank=True, null=True)),
                ('vrup', models.TextField(blank=True, null=True)),
                ('a11', models.TextField(blank=True, null=True)),
                ('a22', models.TextField(blank=True, null=True)),
                ('a33', models.TextField(blank=True, null=True)),
                ('a31', models.TextField(blank=True, null=True)),
                ('a32', models.TextField(blank=True, null=True)),
                ('a12', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_uses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_uses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('parameters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visualize.Parameters')),
                ('user', models.CharField(max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('upload_date', models.DateTimeField(verbose_name='upload date')),
                ('comments', models.TextField(default='')),
            ],
            bases=('visualize.parameters',),
        ),
        migrations.AddField(
            model_name='group',
            name='projects',
            field=models.ManyToManyField(to='visualize.Project'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='groups',
            field=models.ManyToManyField(to='visualize.Group'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='projects',
            field=models.ManyToManyField(to='visualize.Project'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='tags',
            field=models.ManyToManyField(to='visualize.Tag'),
        ),
        migrations.AddField(
            model_name='data_product',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Simulation'),
        ),
    ]
