# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc1', models.TextField()),
                ('bc2', models.TextField()),
                ('dt', models.TextField()),
                ('dx', models.TextField()),
                ('eplasticity', models.TextField()),
                ('faultnormal', models.TextField()),
                ('friction', models.TextField()),
                ('ihypo', models.TextField()),
                ('np3', models.TextField()),
                ('npml', models.TextField()),
                ('nt', models.TextField()),
                ('nn', models.TextField()),
                ('rundir', models.TextField()),
                ('pcdep', models.TextField(blank=True, null=True)),
                ('rcrit', models.TextField(blank=True, null=True)),
                ('delts', models.TextField(blank=True, null=True)),
                ('tm0', models.TextField(blank=True, null=True)),
                ('tmnucl', models.TextField(blank=True, null=True)),
                ('trelax', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rupture_Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_extent', models.TextField()),
                ('magnitude', models.TextField()),
                ('del_tau', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, unique=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True, verbose_name='upload date')),
                ('comments', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=200, null=True)),
                ('fieldname', models.CharField(max_length=200)),
                ('val', models.CharField(blank=True, max_length=200, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation_Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('shape', models.CharField(max_length=200)),
                ('indices', models.CharField(max_length=200)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('simulation', models.ManyToManyField(to='visualize.Simulation')),
            ],
        ),
        migrations.AddField(
            model_name='rupture_parameters',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualize.Simulation'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualize.Simulation'),
        ),
    ]
