# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rupture_parameters',
            name='del_tau',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rupture_parameters',
            name='fault_extent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rupture_parameters',
            name='magnitude',
            field=models.FloatField(),
        ),
    ]
