# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_auto_20160809_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='id',
        ),
        migrations.AlterField(
            model_name='parameters',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='visualize.Simulation'),
        ),
    ]
