# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_auto_20160515_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='upload date'),
        ),
    ]
