# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0003_auto_20160816_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnePoint',
            fields=[
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='visualize.Simulation')),
                ('avg_slip_tr', models.FloatField()),
                ('avg_psv_tr', models.FloatField()),
                ('avg_vrup_tr', models.FloatField()),
                ('std_slip_tr', models.FloatField()),
                ('std_psv_tr', models.FloatField()),
                ('std_vrup_tr', models.FloatField()),
                ('avg_slip_sa', models.FloatField()),
                ('avg_psv_sa', models.FloatField()),
                ('avg_vrup_sa', models.FloatField()),
                ('std_slip_sa', models.FloatField()),
                ('std_psv_sa', models.FloatField()),
                ('std_vrup_sa', models.FloatField()),
                ('med_slip_sa', models.FloatField()),
                ('med_psv_sa', models.FloatField()),
                ('med_vrup_sa', models.FloatField()),
                ('mad_slip_sa', models.FloatField()),
                ('mad_psv_sa', models.FloatField()),
                ('mad_vrup_sa', models.FloatField()),
                ('med_del_tau', models.FloatField()),
                ('avg_del_tau', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rupture_parameters',
            name='id',
        ),
        migrations.AlterField(
            model_name='rupture_parameters',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='visualize.Simulation'),
        ),
    ]
