# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0003_auto_20160515_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='bc1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='bc2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='dx',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='ihypo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='np3',
            field=models.TextField(),
        ),
    ]
