# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0004_auto_20160826_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='rnucl',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
