# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0005_parameters_rnucl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='rnucl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
