# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0006_auto_20160826_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onepoint',
            old_name='std_psv_tr',
            new_name='td_psv_tr',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='rnucl',
        ),
    ]
