# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0007_auto_20160826_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onepoint',
            old_name='td_psv_tr',
            new_name='std_psv_tr',
        ),
    ]
