# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0008_auto_20160826_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Simulation')),
            ],
        ),
    ]
