# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0009_figure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation_input',
            old_name='fieldname',
            new_name='field',
        ),
    ]
