# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0011_auto_20160827_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 27, 20, 31, 12, 515684, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
