# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0012_auto_20160827_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simulation_input',
            unique_together=set([('simulation', 'file')]),
        ),
        migrations.AlterUniqueTogether(
            name='simulation_output',
            unique_together=set([('simulation', 'file', 'field')]),
        ),
    ]
